// Code generated by entc, DO NOT EDIT.

package notes

import (
	"time"
)

const (
	// Label holds the string label denoting the notes type in the database.
	Label = "notes"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldPrivate holds the string denoting the private field in the database.
	FieldPrivate = "private"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"

	// Table holds the table name of the notes in the database.
	Table = "notes"
)

// Columns holds all SQL columns for notes fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldContent,
	FieldPrivate,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPrivate holds the default value on creation for the Private field.
	DefaultPrivate bool
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
)
