// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/GhvstCode/LR-ENT/ent/migrate"

	"github.com/GhvstCode/LR-ENT/ent/notes"

	"github.com/facebook/ent/dialect"
	"github.com/facebook/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Notes is the client for interacting with the Notes builders.
	Notes *NotesClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Notes = NewNotesClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Notes:  NewNotesClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(*sql.Driver).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: &txDriver{tx: tx, drv: c.driver}, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		config: cfg,
		Notes:  NewNotesClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Notes.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Notes.Use(hooks...)
}

// NotesClient is a client for the Notes schema.
type NotesClient struct {
	config
}

// NewNotesClient returns a client for the Notes from the given config.
func NewNotesClient(c config) *NotesClient {
	return &NotesClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `notes.Hooks(f(g(h())))`.
func (c *NotesClient) Use(hooks ...Hook) {
	c.hooks.Notes = append(c.hooks.Notes, hooks...)
}

// Create returns a create builder for Notes.
func (c *NotesClient) Create() *NotesCreate {
	mutation := newNotesMutation(c.config, OpCreate)
	return &NotesCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// BulkCreate returns a builder for creating a bulk of Notes entities.
func (c *NotesClient) CreateBulk(builders ...*NotesCreate) *NotesCreateBulk {
	return &NotesCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Notes.
func (c *NotesClient) Update() *NotesUpdate {
	mutation := newNotesMutation(c.config, OpUpdate)
	return &NotesUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NotesClient) UpdateOne(n *Notes) *NotesUpdateOne {
	mutation := newNotesMutation(c.config, OpUpdateOne, withNotes(n))
	return &NotesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NotesClient) UpdateOneID(id int) *NotesUpdateOne {
	mutation := newNotesMutation(c.config, OpUpdateOne, withNotesID(id))
	return &NotesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Notes.
func (c *NotesClient) Delete() *NotesDelete {
	mutation := newNotesMutation(c.config, OpDelete)
	return &NotesDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *NotesClient) DeleteOne(n *Notes) *NotesDeleteOne {
	return c.DeleteOneID(n.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *NotesClient) DeleteOneID(id int) *NotesDeleteOne {
	builder := c.Delete().Where(notes.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NotesDeleteOne{builder}
}

// Query returns a query builder for Notes.
func (c *NotesClient) Query() *NotesQuery {
	return &NotesQuery{config: c.config}
}

// Get returns a Notes entity by its id.
func (c *NotesClient) Get(ctx context.Context, id int) (*Notes, error) {
	return c.Query().Where(notes.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NotesClient) GetX(ctx context.Context, id int) *Notes {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *NotesClient) Hooks() []Hook {
	return c.hooks.Notes
}
