// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/GhvstCode/LR-ENT/ent/notes"
	"github.com/GhvstCode/LR-ENT/ent/predicate"
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// NotesUpdate is the builder for updating Notes entities.
type NotesUpdate struct {
	config
	hooks      []Hook
	mutation   *NotesMutation
	predicates []predicate.Notes
}

// Where adds a new predicate for the builder.
func (nu *NotesUpdate) Where(ps ...predicate.Notes) *NotesUpdate {
	nu.predicates = append(nu.predicates, ps...)
	return nu
}

// SetTitle sets the Title field.
func (nu *NotesUpdate) SetTitle(s string) *NotesUpdate {
	nu.mutation.SetTitle(s)
	return nu
}

// SetContent sets the Content field.
func (nu *NotesUpdate) SetContent(s string) *NotesUpdate {
	nu.mutation.SetContent(s)
	return nu
}

// SetPrivate sets the Private field.
func (nu *NotesUpdate) SetPrivate(b bool) *NotesUpdate {
	nu.mutation.SetPrivate(b)
	return nu
}

// SetNillablePrivate sets the Private field if the given value is not nil.
func (nu *NotesUpdate) SetNillablePrivate(b *bool) *NotesUpdate {
	if b != nil {
		nu.SetPrivate(*b)
	}
	return nu
}

// SetCreatedAt sets the created_at field.
func (nu *NotesUpdate) SetCreatedAt(t time.Time) *NotesUpdate {
	nu.mutation.SetCreatedAt(t)
	return nu
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (nu *NotesUpdate) SetNillableCreatedAt(t *time.Time) *NotesUpdate {
	if t != nil {
		nu.SetCreatedAt(*t)
	}
	return nu
}

// Mutation returns the NotesMutation object of the builder.
func (nu *NotesUpdate) Mutation() *NotesMutation {
	return nu.mutation
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (nu *NotesUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(nu.hooks) == 0 {
		affected, err = nu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NotesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			nu.mutation = mutation
			affected, err = nu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(nu.hooks) - 1; i >= 0; i-- {
			mut = nu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (nu *NotesUpdate) SaveX(ctx context.Context) int {
	affected, err := nu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nu *NotesUpdate) Exec(ctx context.Context) error {
	_, err := nu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nu *NotesUpdate) ExecX(ctx context.Context) {
	if err := nu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (nu *NotesUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   notes.Table,
			Columns: notes.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: notes.FieldID,
			},
		},
	}
	if ps := nu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nu.mutation.Title(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notes.FieldTitle,
		})
	}
	if value, ok := nu.mutation.Content(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notes.FieldContent,
		})
	}
	if value, ok := nu.mutation.Private(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: notes.FieldPrivate,
		})
	}
	if value, ok := nu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notes.FieldCreatedAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, nu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notes.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// NotesUpdateOne is the builder for updating a single Notes entity.
type NotesUpdateOne struct {
	config
	hooks    []Hook
	mutation *NotesMutation
}

// SetTitle sets the Title field.
func (nuo *NotesUpdateOne) SetTitle(s string) *NotesUpdateOne {
	nuo.mutation.SetTitle(s)
	return nuo
}

// SetContent sets the Content field.
func (nuo *NotesUpdateOne) SetContent(s string) *NotesUpdateOne {
	nuo.mutation.SetContent(s)
	return nuo
}

// SetPrivate sets the Private field.
func (nuo *NotesUpdateOne) SetPrivate(b bool) *NotesUpdateOne {
	nuo.mutation.SetPrivate(b)
	return nuo
}

// SetNillablePrivate sets the Private field if the given value is not nil.
func (nuo *NotesUpdateOne) SetNillablePrivate(b *bool) *NotesUpdateOne {
	if b != nil {
		nuo.SetPrivate(*b)
	}
	return nuo
}

// SetCreatedAt sets the created_at field.
func (nuo *NotesUpdateOne) SetCreatedAt(t time.Time) *NotesUpdateOne {
	nuo.mutation.SetCreatedAt(t)
	return nuo
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (nuo *NotesUpdateOne) SetNillableCreatedAt(t *time.Time) *NotesUpdateOne {
	if t != nil {
		nuo.SetCreatedAt(*t)
	}
	return nuo
}

// Mutation returns the NotesMutation object of the builder.
func (nuo *NotesUpdateOne) Mutation() *NotesMutation {
	return nuo.mutation
}

// Save executes the query and returns the updated entity.
func (nuo *NotesUpdateOne) Save(ctx context.Context) (*Notes, error) {
	var (
		err  error
		node *Notes
	)
	if len(nuo.hooks) == 0 {
		node, err = nuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NotesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			nuo.mutation = mutation
			node, err = nuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(nuo.hooks) - 1; i >= 0; i-- {
			mut = nuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (nuo *NotesUpdateOne) SaveX(ctx context.Context) *Notes {
	node, err := nuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nuo *NotesUpdateOne) Exec(ctx context.Context) error {
	_, err := nuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nuo *NotesUpdateOne) ExecX(ctx context.Context) {
	if err := nuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (nuo *NotesUpdateOne) sqlSave(ctx context.Context) (_node *Notes, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   notes.Table,
			Columns: notes.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: notes.FieldID,
			},
		},
	}
	id, ok := nuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Notes.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := nuo.mutation.Title(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notes.FieldTitle,
		})
	}
	if value, ok := nuo.mutation.Content(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notes.FieldContent,
		})
	}
	if value, ok := nuo.mutation.Private(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: notes.FieldPrivate,
		})
	}
	if value, ok := nuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notes.FieldCreatedAt,
		})
	}
	_node = &Notes{config: nuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues()
	if err = sqlgraph.UpdateNode(ctx, nuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notes.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
